### ISSUE TITLE
rcmgr: [Tracking issue] Resource management and protection documentation and education

### ISSUE THREAD

**Issue by BigLep** [libp2p/go-libp2p#1711]
Below are the mechanisms go-libp2p consumers will have to learn about resource management and resource protection:

- [x] https://github.com/libp2p/go-libp2p-resource-manager/issues/26
- [x] https://github.com/libp2p/docs/issues/158
- [x] https://github.com/libp2p/docs/issues/153
- [x] https://github.com/libp2p/go-libp2p-resource-manager/issues/27
- [x] https://github.com/libp2p/go-libp2p-resource-manager/issues/28

**Comment by MarcoPolo** [comment]
Closing this since we've checked all the boxes :)
