### ISSUE TITLE
Tracking Issue: early muxer selection

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1789]
eta: 2022Q4

Discussed with @julian88110 yesterday: We'll target the completion of this feature for the v0.24 release. The TLS part is almost done, and it is expected that the Noise part can be completed in the next 1-2 weeks.

Done criteria:
* [x] early muxer selection when using TLS (#1772)
* [x] early muxer selection when using Noise (https://github.com/libp2p/go-libp2p/pull/1813)
* [x] https://github.com/libp2p/go-libp2p/issues/1854
* [x] https://github.com/libp2p/go-libp2p/issues/1836
* [x] double check that the [Testground cross-version test](https://github.com/libp2p/test-plans/blob/master/ping/_compositions/go-cross-versions.toml) hits these new code paths
* [x] spec merged: https://github.com/libp2p/specs/pull/446
* [x] docs: https://github.com/libp2p/docs/issues/213
* [ ] #1889

**Comment by marten-seemann** [comment]
Closing this issue, as this is done. The remaining work is captured by #1889.
