### ISSUE TITLE
go-libp2p 2022 Q4/2023 Q1 Roadmap

### ISSUE THREAD

**Issue by p-shahi** [libp2p/go-libp2p#1806]
> 🛣🗺 Roadmap document: https://github.com/libp2p/go-libp2p/blob/master/ROADMAP.md

children:
* https://github.com/libp2p/go-libp2p/issues/1811
* https://github.com/libp2p/go-libp2p/issues/1807
* https://github.com/libp2p/go-libp2p/issues/1808
* https://github.com/libp2p/go-libp2p/issues/2034

eta: 2023Q2

### Current status of Roadmap
2022-10-20: Accepted. Internal go-libp2p stakeholders have aligned on this roadmap.

### Description
This issue is intended to capture discussion around the [go-libp2p 2022 Q4/2023 Q1 Roadmap](https://github.com/libp2p/go-libp2p/blob/master/ROADMAP.md).

Because GitHub doesn't have any feature to comment on Markdown files, please use this issue to leave any feedback, proposals, etc.

For internal discussions on Notion, please see: https://www.notion.so/pl-strflt/go-libp2p-22-Q4-23-Q1-Product-Roadmap-48bc31fd5b394a29812d6cda624fffa0

### Roadmap drafts:
1st draft: https://github.com/libp2p/go-libp2p/pull/1784
2nd draft: https://github.com/libp2p/go-libp2p/pull/1831

**Comment by BigLep** [comment]
Related PRs:
https://github.com/libp2p/go-libp2p/pull/1784
https://github.com/libp2p/go-libp2p/pull/1804

**Comment by p-shahi** [comment]
Open questions/feedback from @BigLep 

- [ ] https://github.com/libp2p/go-libp2p/pull/1784#pullrequestreview-1135077135
- [ ] https://github.com/libp2p/go-libp2p/pull/1784#discussion_r990501102
- [ ] https://github.com/libp2p/go-libp2p/pull/1784#discussion_r990501140
- [ ] https://github.com/libp2p/go-libp2p/pull/1784#discussion_r990501345
- [ ] https://github.com/libp2p/go-libp2p/pull/1784#discussion_r990504886
- [ ] https://github.com/libp2p/go-libp2p/pull/1784#discussion_r990505847
- [ ] https://github.com/libp2p/go-libp2p/pull/1784#discussion_r990507168

**Comment by BigLep** [comment]
@p-shahi : in looking at https://github.com/libp2p/go-libp2p/blob/master/ROADMAP.md fresh, here are the feedback items I have:

1. I don't think we should have both "A.1⚡Handshakes at the Speed of Light" and  "E.1 🧪 Future-proof testing - RTT test for Early Muxer Negotiation".  I think E.1 is really just part of A.1.  We're not going to mark A.1 done until we have E.1 as part of it.  Specifically, I'm suggesting we inline E.1 into the A.1 description.  It reduces clutter and makes it clear that we do this kind of testing for all new functionality we develop.  It's not an effort that's tracked separately.

2. "A.1⚡Handshakes at the Speed of Light" and "D.1 📺 Universal Browser Connectivity" are trains that are in motion that we're not going to slow down or divert resources from.  We're committed to those and we're going to make them happen.  That said, I think all remaining initiative gas should be poured into interoperability testing.  I know we have to work in tandem with Laurent/Testground, but I want to get all of the go-libp2p side of the interoperability matrix filled in as soon as possible.  I think that is worthy of its own milestone in go-libp2p.  We can link out to "libp2p/test-plans" discussion, but there is specific work that go-libp2p needs to do.  I'm sorry that wasn't clear, but that was what I was trying to get at [here](https://github.com/libp2p/go-libp2p/pull/1784#discussion_r990504886).  Concretely, I think we should have a milestone for go-libp2p around "go-libp2 does interoperability testing across all important dimensions".

3. I like that we're jumping into performance benchmarking soon.  That said, I would do it after we lick interoperability testing (but before other items like you have listed currently).

4. In terms of "End of Q4 (December)" items, I would invert the order from a priority regard.  D.1 > C > B.1.  At the minimum, I would put metrics (C) ahead of smart dialing (B.1).

5. Compared to other roadmaps where someone sees target month, milestone name, and description, I think we're missing a bit here requiring someone to scroll down to the proper section to learn more.  Not critical, but making this a link would help.

6. Concerning discoverability of this roadmap, I see we added it to the README and pinned this issue (great - thanks).  Will we also link from https://github.com/libp2p/specs/blob/master/ROADMAP.md ?

7. Related to #6, where will discuss libp2p's core tenants of security, stability, and performance?

If the above gets incorporated, I think we are good to say we're "internally aligned".  I understand though if we need another round of back and forth.  I'm happy to have a quick sync as well if that helps.

Thank you!

**Comment by p-shahi** [comment]
@BigLep please see: https://github.com/libp2p/go-libp2p/pull/1831
I had this open but as draft (without reviewers assigned) so it was likely you didn't see it during your pass through yesterday.
#1831 addresses 1, 3, 4, 5, and 7.

Regarding 2, I opted to move the testing and benchmarking items to [the test-plans roadmap here](https://github.com/libp2p/test-plans/pull/56). The priority of interop testing is highlighted in the [go-libp2p Roadmap's Benchmarking and Testing section](https://github.com/libp2p/go-libp2p/blob/b1086fb849c39c9203ba9f3bdf1f1b47933903d6/ROADMAP.md#benchmarking-and-testing) and made clear to the reader that it sits high at the list. Since interoperability is a shared concern, it makes sense to house it in the shared test-plans roadmap.

Regarding 6, I can add the links to the Spec roadmap too. Will have to do the same for Rust and JS.

**Comment by BigLep** [comment]
ACK - sounds good @p-shahi .  I also reviewed/approved #1831.

**Comment by marten-seemann** [comment]
Closing this issue, since the roadmap was agreed upon and is merged. Potential changes to the roadmap can be suggested by creating a PR against that file.

**Comment by BigLep** [comment]
Maybe there have been other conversations with @p-shahi , but the intent of having this open issue is so:
1. Single place people can subscribe to get roadmap updates and ask questions
2. Have a pinned issue for discoverability
3. Have a single place to link update PRs to

**Comment by marten-seemann** [comment]
Sorry!

**Comment by marten-seemann** [comment]
Closing this issue since Q1 is over.
