### ISSUE TITLE
Tracking issue: Finish WebTransport Support

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1827]
We shipped experimental WebTransport support in v0.23.0. There are a few things we still need to do to completely finish the project.

- [x] archive https://github.com/marten-seemann/go-libp2p-webtransport/
- [x] docs entry for WebTransport: https://github.com/libp2p/docs/pull/198 
- [x] get the WebTransport spec merged: https://github.com/libp2p/specs/pull/404
- [x] https://github.com/libp2p/go-libp2p/issues/1826
- [x] https://github.com/libp2p/go-libp2p/issues/1824
- [x] https://github.com/libp2p/go-libp2p/issues/1825
- [x] https://github.com/libp2p/go-libp2p/issues/1759

Once js-libp2p has released WebTransport support:
- [x] write an announcement to shipped@ mailing list
- [x] write a blog post: https://github.com/libp2p/blog/pull/11

And then, assuming that our experiment (see https://github.com/protocol/bifrost-infra/issues/2114) is successful:
- [x] https://github.com/libp2p/go-libp2p/pull/1915

**Comment by BigLep** [comment]
This is great - thanks @marten-seemann !

> optional: write a blog post

I would remove optional.  We've got to to do this.  We have a lot of "tree shaking" to do here to make sure folks are awareof what is possible!

**Comment by p-shahi** [comment]
https://github.com/ipfs/kubo/releases/tag/v0.18.0 is out, I think we can do the shipped email now @marten-seemann
