### ISSUE TITLE
v0.36

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/go-libp2p#2778]
## 🗺 What's left for release

- [x] https://github.com/libp2p/go-libp2p/issues/2657
- [x] #2858 
- [x] https://github.com/libp2p/go-libp2p/pull/2868
- [x] https://github.com/libp2p/go-libp2p/issues/2422

## ⚠️ Breaking Changes ⚠️
- `Conn.NewStream`, `Network.NewStream` and `Host.NewStream` timeout after 15 seconds, if no deadline is specified on the provided `ctx`. 

### AutoNAT v2
- This release ships with an autonat-v2 service. The service allows users to check their rechability for individual addresses. 
- For more details of the protocol, refer to the [specs](https://github.com/libp2p/specs/blob/autonat-v2/autonat/autonat-v2.md): 
- BasicHost doesn't use autonat-v2 right now for verifying reachability. Once there are enough autonat-v2 servers in the IPFS network, we will use autonat-v2 to infer the node's reachability, and deprecate autonat-v1. 
- AutoNAT v2 is disabled by default. To enable, use the `EnableAutoNATV2` [option](https://github.com/libp2p/go-libp2p/blob/master/options.go#L614).

#### WebRTC Direct transport is now Non-Experimental
- `/webrtc-direct` is now enabled by default. 
- We will provide patch releases for any bug fixes or security vulnerabilities in WebRTC just like other transports. 
#### Share listening port with QUIC
- WebRTC Direct nodes, like WebTransport nodes can use the same port as the QUIC transport.
```go
	h, err = libp2p.New(
		libp2p.ListenAddrStrings(
			"/ip4/0.0.0.0/udp/4242/quic-v1",
			"/ip4/0.0.0.0/udp/4242/webrtc-direct"),
	)
```
- Servers now don't need to open an extra port in their firewalls. This also enables WebRTC Direct nodes to infer their publicly visible address on machines behind a NAT. 

        

## Changelog

< changelog generated by scripts/mkreleaselog >

## ✅ Release Checklist

- [ ] **Stage 0 - Finishing Touches**
    - [ ] Go through relevant libp2p repos looking for unreleased changes that should make it into the release. If you find any, cut releases.
    - [ ] Run `go get -u ./...` to see if there are any out-of-date deps that look important. If there are, bubble them. Try to avoid _directly_ updating indirect deps in go-libp2p's `go.mod` when possible.
- [ ] **Stage 1 - Release**
  - [ ] Publish the release through the GitHub UI, adding the release notes. Some users rely on this to receive notifications of new releases.
  - [ ] Announce the release on the [discuss.libp2p.io](https://discuss.libp2p.io).
- [ ] **Stage 2 - Update Upstream**
  - [ ] Update the examples to the final release
  - [ ] Update the upstream dependencies to the final release and create PRs.
    - [ ] [filecoin-project/lotus](https://github.com/filecoin-project/lotus)
    - [ ] [go-libp2p-kad-dht](https://github.com/libp2p/go-libp2p-kad-dht/)
    - [ ] [go-libp2p-pubsub](https://github.com/libp2p/go-libp2p-pubsub) (In case of breaking changes.)
    - [ ] [ipfs/kubo](https://github.com/ipfs/kubo)
  - [ ] Add new release to interop tester in [test-plans](https://github.com/libp2p/test-plans/)
- [ ] Make required changes to the release process.

```[tasklist]
### Tasks
- [ ] https://github.com/libp2p/go-libp2p/issues/2899
- [ ] https://github.com/libp2p/go-libp2p/pull/2903
```

**Comment by achingbrain** [comment]
Very excited for #2657! 👏 👏 👏
