### ISSUE TITLE
Error Codes Tracking Issue

### ISSUE THREAD

**Issue by sukunrt** [libp2p/go-libp2p#3053]
## Specs
- [ ] https://github.com/libp2p/specs/pull/623
- [ ] https://github.com/libp2p/specs/pull/622

## Implementation
- [ ] https://github.com/libp2p/go-libp2p/pull/2927
- [ ] Setup Registry: https://github.com/libp2p/error-codes/
- [ ] Yamux Extension: https://github.com/libp2p/go-yamux/pull/121

## Applications
- [ ] AutoNAT v2
- [ ] Circuit v2
- [ ] Identify?
- [ ] Gossipsub
- [ ] Kad-dht
