### ISSUE TITLE
Signed Peer Records

### ISSUE THREAD

**Issue by yusefnapora** [libp2p/go-libp2p#776]
This is a meta-issue to track the progress of implementing the signed Peer Records proposed in https://github.com/libp2p/specs/pull/217 and #761 

### Core implementation

The basic functionality is currently spread through three open PRs in various repos:

- https://github.com/libp2p/go-libp2p-core/pull/73
  - defines `Envelope` and `PeerRecord` types and signing / marshaling logic
  - adds a `CertifiedAddrBook` interface to add addresses from `PeerRecord`s to the `Peerstore`
  - adds two new event types:
    - `EvtLocalAddressesUpdated` is sent when our listen addresses change. Includes a snapshot of current listen addrs, and may also have diffs against the previous state.
    - `EvtLocalPeerRecordUpdated` is sent when we have a new signed `PeerRecord` to distribute to other peers.

- https://github.com/libp2p/go-libp2p-peerstore/pull/98
  - implements the `CertifiedAddrBook` interface in the memory and datastore `AddrBook`s

- go-libp2p https://github.com/libp2p/go-libp2p/pull/747
  - updates the `IDService` to exchange signed `PeerRecord`s during the `identify` protocol, and add records for remote peers to the peerstore
  - changes the way `identify/push` is triggered by getting the event bus into the mix:
    - updates `BasicHost` to emit `EvtLocalAddressesUpdated` events when it detects a change in listen addresses instead of directly triggering an `identify/push`
    - adds a `peerRecordManager` component to the `IDService`, which listens for `EvtLocalAddressesUpdated` and creates new signed `PeerRecord`s, which it sends out on the event bus in an `EvtLocalPeerRecordUpdated`
    - updates the `IDService` to listen for `EvtLocalPeerRecordUpdated` and trigger an `identify/push` update

These should be merged in order, and we should tag new releases and update the dependencies in the peerstore and go-libp2p PRs to stop pointing at specific branch commits. So the merge strategy is:

- [x] squash & merge https://github.com/libp2p/go-libp2p-core/pull/73
- [x] tag new go-libp2p-core release
- [x] update https://github.com/libp2p/go-libp2p-peerstore/pull/98 to point at new -core, squash & merge
- [x] tag new go-libp2p-peerstore release
- [x] update https://github.com/libp2p/go-libp2p/pull/747 with new -core and -peerstore deps, squash & merge
- [x] tag new go-libp2p release

### Components that will use PeerRecords

Once the above PRs are landed, we can integrate signed `PeerRecord`s into various libp2p components:

- [x] [peer exchange in gossipsub](https://github.com/libp2p/go-libp2p-pubsub/pull/234)
  - [x] update to track recent API changes (https://github.com/libp2p/go-libp2p-pubsub/pull/257)
- [ ] kad-dht
- [ ] mDNS

**Comment by raulk** [comment]
- [ ] Add an entry to the [multicodec](https://github.com/multiformats/multicodec) table for peer records.

**Comment by raulk** [comment]
go-libp2p v0.9.0, launched yesterday, has support for signed peer records. Read all about it: https://github.com/libp2p/go-libp2p/releases/tag/v0.9.0.
